// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package server

import (
	"context"

	"lixiandea.github.com/go-zero-mall/apps/user/rpc/internal/logic"
	"lixiandea.github.com/go-zero-mall/apps/user/rpc/internal/svc"
	"lixiandea.github.com/go-zero-mall/apps/user/rpc/rpc"
)

type RpcServer struct {
	svcCtx *svc.ServiceContext
	rpc.UnimplementedRpcServer
}

func NewRpcServer(svcCtx *svc.ServiceContext) *RpcServer {
	return &RpcServer{
		svcCtx: svcCtx,
	}
}

func (s *RpcServer) Register(ctx context.Context, in *rpc.RegisterRequest) (*rpc.RegisterResponse, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *RpcServer) Login(ctx context.Context, in *rpc.LoginRequest) (*rpc.LoginResponse, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *RpcServer) GetUserInfo(ctx context.Context, in *rpc.UserInfoRequest) (*rpc.UserInfoResponse, error) {
	l := logic.NewGetUserInfoLogic(ctx, s.svcCtx)
	return l.GetUserInfo(in)
}
